# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20161229_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageRelatedCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon', models.CharField(max_length=30)),
                ('header', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='descr1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='descr2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='descr3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='subheader1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='subheader2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='subheader3',
        ),
        migrations.AddField(
            model_name='homepagerelatedcards',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_cards', to='home.HomePage'),
        ),
    ]
