# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20161230_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagerelatedcards',
            name='site_path',
            field=models.CharField(default='/home', max_length=255),
            preserve_default=False,
        ),
    ]
