# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepagerelatedcards_site_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagerelatedcards',
            name='label',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
