# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepagerelatedcards_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagerelatedcards',
            name='tooltip',
            field=models.CharField(default='ok', max_length=255),
            preserve_default=False,
        ),
    ]
